// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/casbin/ent-adapter/ent/casbinrule"
)

// CasbinRule is the model entity for the CasbinRule schema.
type CasbinRule struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Ptype holds the value of the "Ptype" field.
	Ptype string `json:"Ptype,omitempty"`
	// V0 holds the value of the "V0" field.
	V0 string `json:"V0,omitempty"`
	// V1 holds the value of the "V1" field.
	V1 string `json:"V1,omitempty"`
	// V2 holds the value of the "V2" field.
	V2 string `json:"V2,omitempty"`
	// V3 holds the value of the "V3" field.
	V3 string `json:"V3,omitempty"`
	// V4 holds the value of the "V4" field.
	V4 string `json:"V4,omitempty"`
	// V5 holds the value of the "V5" field.
	V5           string `json:"V5,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CasbinRule) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case casbinrule.FieldID:
			values[i] = new(sql.NullInt64)
		case casbinrule.FieldPtype, casbinrule.FieldV0, casbinrule.FieldV1, casbinrule.FieldV2, casbinrule.FieldV3, casbinrule.FieldV4, casbinrule.FieldV5:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CasbinRule fields.
func (_m *CasbinRule) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case casbinrule.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case casbinrule.FieldPtype:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Ptype", values[i])
			} else if value.Valid {
				_m.Ptype = value.String
			}
		case casbinrule.FieldV0:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field V0", values[i])
			} else if value.Valid {
				_m.V0 = value.String
			}
		case casbinrule.FieldV1:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field V1", values[i])
			} else if value.Valid {
				_m.V1 = value.String
			}
		case casbinrule.FieldV2:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field V2", values[i])
			} else if value.Valid {
				_m.V2 = value.String
			}
		case casbinrule.FieldV3:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field V3", values[i])
			} else if value.Valid {
				_m.V3 = value.String
			}
		case casbinrule.FieldV4:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field V4", values[i])
			} else if value.Valid {
				_m.V4 = value.String
			}
		case casbinrule.FieldV5:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field V5", values[i])
			} else if value.Valid {
				_m.V5 = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CasbinRule.
// This includes values selected through modifiers, order, etc.
func (_m *CasbinRule) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CasbinRule.
// Note that you need to call CasbinRule.Unwrap() before calling this method if this CasbinRule
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CasbinRule) Update() *CasbinRuleUpdateOne {
	return NewCasbinRuleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CasbinRule entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CasbinRule) Unwrap() *CasbinRule {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CasbinRule is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CasbinRule) String() string {
	var builder strings.Builder
	builder.WriteString("CasbinRule(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("Ptype=")
	builder.WriteString(_m.Ptype)
	builder.WriteString(", ")
	builder.WriteString("V0=")
	builder.WriteString(_m.V0)
	builder.WriteString(", ")
	builder.WriteString("V1=")
	builder.WriteString(_m.V1)
	builder.WriteString(", ")
	builder.WriteString("V2=")
	builder.WriteString(_m.V2)
	builder.WriteString(", ")
	builder.WriteString("V3=")
	builder.WriteString(_m.V3)
	builder.WriteString(", ")
	builder.WriteString("V4=")
	builder.WriteString(_m.V4)
	builder.WriteString(", ")
	builder.WriteString("V5=")
	builder.WriteString(_m.V5)
	builder.WriteByte(')')
	return builder.String()
}

// CasbinRules is a parsable slice of CasbinRule.
type CasbinRules []*CasbinRule
