// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/casbin/ent-adapter/ent/casbinrule"
	"github.com/casbin/ent-adapter/ent/predicate"
)

// CasbinRuleUpdate is the builder for updating CasbinRule entities.
type CasbinRuleUpdate struct {
	config
	hooks    []Hook
	mutation *CasbinRuleMutation
}

// Where appends a list predicates to the CasbinRuleUpdate builder.
func (_u *CasbinRuleUpdate) Where(ps ...predicate.CasbinRule) *CasbinRuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPtype sets the "Ptype" field.
func (_u *CasbinRuleUpdate) SetPtype(v string) *CasbinRuleUpdate {
	_u.mutation.SetPtype(v)
	return _u
}

// SetNillablePtype sets the "Ptype" field if the given value is not nil.
func (_u *CasbinRuleUpdate) SetNillablePtype(v *string) *CasbinRuleUpdate {
	if v != nil {
		_u.SetPtype(*v)
	}
	return _u
}

// SetV0 sets the "V0" field.
func (_u *CasbinRuleUpdate) SetV0(v string) *CasbinRuleUpdate {
	_u.mutation.SetV0(v)
	return _u
}

// SetNillableV0 sets the "V0" field if the given value is not nil.
func (_u *CasbinRuleUpdate) SetNillableV0(v *string) *CasbinRuleUpdate {
	if v != nil {
		_u.SetV0(*v)
	}
	return _u
}

// SetV1 sets the "V1" field.
func (_u *CasbinRuleUpdate) SetV1(v string) *CasbinRuleUpdate {
	_u.mutation.SetV1(v)
	return _u
}

// SetNillableV1 sets the "V1" field if the given value is not nil.
func (_u *CasbinRuleUpdate) SetNillableV1(v *string) *CasbinRuleUpdate {
	if v != nil {
		_u.SetV1(*v)
	}
	return _u
}

// SetV2 sets the "V2" field.
func (_u *CasbinRuleUpdate) SetV2(v string) *CasbinRuleUpdate {
	_u.mutation.SetV2(v)
	return _u
}

// SetNillableV2 sets the "V2" field if the given value is not nil.
func (_u *CasbinRuleUpdate) SetNillableV2(v *string) *CasbinRuleUpdate {
	if v != nil {
		_u.SetV2(*v)
	}
	return _u
}

// SetV3 sets the "V3" field.
func (_u *CasbinRuleUpdate) SetV3(v string) *CasbinRuleUpdate {
	_u.mutation.SetV3(v)
	return _u
}

// SetNillableV3 sets the "V3" field if the given value is not nil.
func (_u *CasbinRuleUpdate) SetNillableV3(v *string) *CasbinRuleUpdate {
	if v != nil {
		_u.SetV3(*v)
	}
	return _u
}

// SetV4 sets the "V4" field.
func (_u *CasbinRuleUpdate) SetV4(v string) *CasbinRuleUpdate {
	_u.mutation.SetV4(v)
	return _u
}

// SetNillableV4 sets the "V4" field if the given value is not nil.
func (_u *CasbinRuleUpdate) SetNillableV4(v *string) *CasbinRuleUpdate {
	if v != nil {
		_u.SetV4(*v)
	}
	return _u
}

// SetV5 sets the "V5" field.
func (_u *CasbinRuleUpdate) SetV5(v string) *CasbinRuleUpdate {
	_u.mutation.SetV5(v)
	return _u
}

// SetNillableV5 sets the "V5" field if the given value is not nil.
func (_u *CasbinRuleUpdate) SetNillableV5(v *string) *CasbinRuleUpdate {
	if v != nil {
		_u.SetV5(*v)
	}
	return _u
}

// Mutation returns the CasbinRuleMutation object of the builder.
func (_u *CasbinRuleUpdate) Mutation() *CasbinRuleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CasbinRuleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CasbinRuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CasbinRuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CasbinRuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CasbinRuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(casbinrule.Table, casbinrule.Columns, sqlgraph.NewFieldSpec(casbinrule.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Ptype(); ok {
		_spec.SetField(casbinrule.FieldPtype, field.TypeString, value)
	}
	if value, ok := _u.mutation.V0(); ok {
		_spec.SetField(casbinrule.FieldV0, field.TypeString, value)
	}
	if value, ok := _u.mutation.V1(); ok {
		_spec.SetField(casbinrule.FieldV1, field.TypeString, value)
	}
	if value, ok := _u.mutation.V2(); ok {
		_spec.SetField(casbinrule.FieldV2, field.TypeString, value)
	}
	if value, ok := _u.mutation.V3(); ok {
		_spec.SetField(casbinrule.FieldV3, field.TypeString, value)
	}
	if value, ok := _u.mutation.V4(); ok {
		_spec.SetField(casbinrule.FieldV4, field.TypeString, value)
	}
	if value, ok := _u.mutation.V5(); ok {
		_spec.SetField(casbinrule.FieldV5, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{casbinrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CasbinRuleUpdateOne is the builder for updating a single CasbinRule entity.
type CasbinRuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CasbinRuleMutation
}

// SetPtype sets the "Ptype" field.
func (_u *CasbinRuleUpdateOne) SetPtype(v string) *CasbinRuleUpdateOne {
	_u.mutation.SetPtype(v)
	return _u
}

// SetNillablePtype sets the "Ptype" field if the given value is not nil.
func (_u *CasbinRuleUpdateOne) SetNillablePtype(v *string) *CasbinRuleUpdateOne {
	if v != nil {
		_u.SetPtype(*v)
	}
	return _u
}

// SetV0 sets the "V0" field.
func (_u *CasbinRuleUpdateOne) SetV0(v string) *CasbinRuleUpdateOne {
	_u.mutation.SetV0(v)
	return _u
}

// SetNillableV0 sets the "V0" field if the given value is not nil.
func (_u *CasbinRuleUpdateOne) SetNillableV0(v *string) *CasbinRuleUpdateOne {
	if v != nil {
		_u.SetV0(*v)
	}
	return _u
}

// SetV1 sets the "V1" field.
func (_u *CasbinRuleUpdateOne) SetV1(v string) *CasbinRuleUpdateOne {
	_u.mutation.SetV1(v)
	return _u
}

// SetNillableV1 sets the "V1" field if the given value is not nil.
func (_u *CasbinRuleUpdateOne) SetNillableV1(v *string) *CasbinRuleUpdateOne {
	if v != nil {
		_u.SetV1(*v)
	}
	return _u
}

// SetV2 sets the "V2" field.
func (_u *CasbinRuleUpdateOne) SetV2(v string) *CasbinRuleUpdateOne {
	_u.mutation.SetV2(v)
	return _u
}

// SetNillableV2 sets the "V2" field if the given value is not nil.
func (_u *CasbinRuleUpdateOne) SetNillableV2(v *string) *CasbinRuleUpdateOne {
	if v != nil {
		_u.SetV2(*v)
	}
	return _u
}

// SetV3 sets the "V3" field.
func (_u *CasbinRuleUpdateOne) SetV3(v string) *CasbinRuleUpdateOne {
	_u.mutation.SetV3(v)
	return _u
}

// SetNillableV3 sets the "V3" field if the given value is not nil.
func (_u *CasbinRuleUpdateOne) SetNillableV3(v *string) *CasbinRuleUpdateOne {
	if v != nil {
		_u.SetV3(*v)
	}
	return _u
}

// SetV4 sets the "V4" field.
func (_u *CasbinRuleUpdateOne) SetV4(v string) *CasbinRuleUpdateOne {
	_u.mutation.SetV4(v)
	return _u
}

// SetNillableV4 sets the "V4" field if the given value is not nil.
func (_u *CasbinRuleUpdateOne) SetNillableV4(v *string) *CasbinRuleUpdateOne {
	if v != nil {
		_u.SetV4(*v)
	}
	return _u
}

// SetV5 sets the "V5" field.
func (_u *CasbinRuleUpdateOne) SetV5(v string) *CasbinRuleUpdateOne {
	_u.mutation.SetV5(v)
	return _u
}

// SetNillableV5 sets the "V5" field if the given value is not nil.
func (_u *CasbinRuleUpdateOne) SetNillableV5(v *string) *CasbinRuleUpdateOne {
	if v != nil {
		_u.SetV5(*v)
	}
	return _u
}

// Mutation returns the CasbinRuleMutation object of the builder.
func (_u *CasbinRuleUpdateOne) Mutation() *CasbinRuleMutation {
	return _u.mutation
}

// Where appends a list predicates to the CasbinRuleUpdate builder.
func (_u *CasbinRuleUpdateOne) Where(ps ...predicate.CasbinRule) *CasbinRuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CasbinRuleUpdateOne) Select(field string, fields ...string) *CasbinRuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CasbinRule entity.
func (_u *CasbinRuleUpdateOne) Save(ctx context.Context) (*CasbinRule, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CasbinRuleUpdateOne) SaveX(ctx context.Context) *CasbinRule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CasbinRuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CasbinRuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CasbinRuleUpdateOne) sqlSave(ctx context.Context) (_node *CasbinRule, err error) {
	_spec := sqlgraph.NewUpdateSpec(casbinrule.Table, casbinrule.Columns, sqlgraph.NewFieldSpec(casbinrule.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CasbinRule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, casbinrule.FieldID)
		for _, f := range fields {
			if !casbinrule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != casbinrule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Ptype(); ok {
		_spec.SetField(casbinrule.FieldPtype, field.TypeString, value)
	}
	if value, ok := _u.mutation.V0(); ok {
		_spec.SetField(casbinrule.FieldV0, field.TypeString, value)
	}
	if value, ok := _u.mutation.V1(); ok {
		_spec.SetField(casbinrule.FieldV1, field.TypeString, value)
	}
	if value, ok := _u.mutation.V2(); ok {
		_spec.SetField(casbinrule.FieldV2, field.TypeString, value)
	}
	if value, ok := _u.mutation.V3(); ok {
		_spec.SetField(casbinrule.FieldV3, field.TypeString, value)
	}
	if value, ok := _u.mutation.V4(); ok {
		_spec.SetField(casbinrule.FieldV4, field.TypeString, value)
	}
	if value, ok := _u.mutation.V5(); ok {
		_spec.SetField(casbinrule.FieldV5, field.TypeString, value)
	}
	_node = &CasbinRule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{casbinrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
