name: Go

on: [push, pull_request]

jobs:

  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: casbin
        ports:
          - 3306:3306
      postgres:
        image: postgres:10.16
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: casbin
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - uses: actions/checkout@v2
      - name: Run Unit tests
        run: go test -v -coverprofile=./profile.cov ./...

      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: ./profile.cov

  semantic-release:
    needs: [test]
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Run semantic-release
        if: github.repository == 'casbin/ent-adapter' && github.event_name == 'push'
        run: |
          npm install --save-dev semantic-release@17.2.4
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}