// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CasbinRule is the predicate function for casbinrule builders.
type CasbinRule func(*sql.Selector)
